---
General:
  OutputFile: "Results/DuneOldUnc.root"
  DUNESamples:
   - "Configs/Samples/SampleHandler_BeamFDStandardRecord.yaml"
  # Nu-FIT
  OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848] #CUDAProb3
  # OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848,  0.5] #NuFAST

  # T2K-like best-fit
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #NuFAST

  OscillatorConfigName: "Configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile:
      - "Configs/CovObjs/OscCov_PDG2021_v2.yaml"
      #- "Configs/CovObjs/BeamParameters2026.yaml"
      - "Configs/CovObjs/tdr_covs/Flux_FD.yaml"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.14


  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 50000
    AutoSave: 10000
    Multicanonical:
      Enabled: false
  Output:
    FileName: "Results/DuneOldUnc.root"
    OUTPUTNAME: "DuneOldUnc.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No

SigmaVar:
  # whether to separate by mach3 mode
  PlotByMode: false
  # whether to seaparate by osc channel
  PlotByChannel: false
  # list of parameters to skip, can include glob patterns e.g: MyParamPrefix_*
  # SkipVector: [sin2th_12, sin2th_23, sin2th_13, delm2_12, delm2_23, delta_cp]
  # parameter values
  SigmaArray: [-1,-0.5,0,0.5,1]

# LLH Scan settings
LLHScan:
  # don't make LLH for certain systematic groups
  # LLHScanSkipVector: ["b_"]
  # Save individual sample contributions to the LLH
  LLHScanBySample: false
  # Number of points we run LLH scans for each systematic
  LLHScanPoints: 10
  # Number of points for 2D scan in each direction
  #2DLLHScanPoints: 20
  # Add physical ranges for special params whose priors/errors may not be well well-defined
  ScanRanges:
    #delta_cp: [-3.14,3.14]

# Tests
Tests:
  SkipChecks: False
  TestResultsFile: tests/test_results/EventRatesV2TDR.txt

Predictive:
# Number of throws from MCMC you want to perform (aim for something like 2k/5k)
  Ntoy: 1000
#Use Full LLH or only sample contribution based on discussion with Asher we almost always only want the sample likelihood
  FullLLH: false
#if false will run posterior predictive
  PriorPredictive: false
  # number of burn in steps
  BurnInSteps: 100
  # Name of file from which we are sampling
  PosteriorFile: "Results/DuneOldUnc.root"
  # Allow to specify to throw/vary only params coming from single group like Xsec. Allow to evaluate errors coming from this group. Can't be mixed with throw single param
  ThrowParamGroupOnly: ["Flux"]
  # Allow to specify to throw/vary only params coming with specified names. Cannot be connected with ThrowParamGroupOnly
  ThrowSingleParams: []
  # When calculating pvalue there are two ways of applying Poissonian fluctuations, both are conceptually identical however standard scales with number of bins while non-standard scales with number of events (making it slow)
  StandardFluctuation: true
  # Whether to print distribution of number of events in every bin, useful only for debug
  DebugHistograms: true
  # Apply additional bounds allowing to do post pred only in normal ordering etc
  ParameterBounds: []
  # Example with normal ordering and upper octant
  #ParameterBounds: [ ["delm2_23", [0, 999]], ["sin2th_23", [0.5, 1] ] ]
  # Will produce posterior predictive distributions with by mode breakdown, can be heavy on RAM
  ByMode: false
  

PredictivePlotting:
  FileTitle: ["Posterior Predictive", "Prior Predictive"]
  #FileTitle: ["Prior Predictive"]
  PosteriorColor: [632, 600] # kRed, kBlue
  RelevantModesName: ["CCQE", "CC2p2h","CC1pipm"]
  # kRed, kMagenta+2, kGreen+1
  RelevantModesColors: [632, 618, 417]
